// Marketing/landing content — ported from the design prototype (ka + en).
// ru falls back to en for now (the prototype ships ka+en; primary audience is ka).
/* eslint-disable */
const RAW = {
  ka: {
    nav: { how: "როგორ მუშაობს", pricing: "ფასები", industries: "ინდუსტრიები", blog: "ბლოგი", signin: "შესვლა", signup: "უფასოდ სცადე", dashboard: "Dashboard" },
    hero: {
      badge: "+12 ლიდი კვირაში — ღამეული ტრაფიკიდან",
      title1: "კლიენტი გელოდება.",
      title2: "შენი ბიზნესი — გძინავს.",
      sub: "ატვირთე FAQ ან მიეცი ვებსაიტის URL — 10 წუთში Peit შენი ბიზნესის AI ასისტენტი ხდება. პასუხობს ქართულად, 24/7, ვებსაიტზე, Telegram-ში და Instagram-ში.",
      cta1: "7 დღე უფასოდ სცადე",
      cta2: "როგორ მუშაობს — 2 წუთი",
      note: "საკრედიტო ბარათი არ გჭირდება · გაუქმება ერთი კლიკით",
      stat1: "0.8წმ", stat1l: "საშუალო პასუხის დრო",
      stat2: "3.2x", stat2l: "მეტი კონვერსია",
      stat3: "24/7", stat3l: "არასოდეს ისვენებს",
    },
    chat: {
      name: "Peit Assistant", status: "ცოცხალია · 0.8წმ", avg: "0.8წმ avg",
      placeholder: "დაწერე შენი კითხვა...",
      msgs: [
        { who: "user", t: "გამარჯობა, ღამის 11-ზე ღიათ ხართ?" },
        { who: "bot", t: "გამარჯობა! 👋 ონლაინ შეკვეთებს 24/7 ვიღებთ. მიტანა თბილისში — 40 წუთამდე. რისი შეკვეთა გსურთ?" },
        { who: "user", t: "ორი პიცა მინდა, სად მივიტანო ლინკი?" },
        { who: "bot", t: "ახლავე გამოგიგზავნით — დაგიფიქსირეთ ნომერიც. გადახდა ბარათით ან ადგილზე. ✅ ლიდი შენახულია." },
      ],
    },
    social: {
      trust: "10,000+ ბიზნესი გვენდობა",
      sub: "საქართველოში ყველაზე სწრაფად მზარდი AI პლატფორმა",
      rating: "4.9", ratingNote: "(320+ შეფასება)",
      logos: ["Online Shop GE","MarShop","SaaS სტარტაპი","Tbilisi Resto","LegalPro GE","FitClub GE","GeoHotel","BeautyStudio","RealEstate GE","MediClinic","TechStartup","FoodDelivery"],
    },
    features: {
      kicker: "ფუნქციები",
      title: "ყველაფერი ერთ ადგილას — შენი მაგივრად მუშაობს",
      sub: "ერთი პლატფორმა, ყველა არხი, ყველა ენა. შენ მხოლოდ შედეგებს ხედავ.",
      items: [
        { t: "24/7 — არასოდეს იძინებს", d: "ღამის, შაბათ-კვირის და დასვენების ტრაფიკი აღარ იკარგება. ყოველი ვიზიტორი 0.8 წამში პასუხს იღებს." },
        { t: "ვებსაიტი, Telegram, Instagram", d: "ერთი ბოტი — ყველა არხზე. საუბრები, ლიდები და ანალიტიკა — ერთ dashboard-ში გროვდება." },
        { t: "ქართულად ბუნებრივად საუბრობს", d: "არა «თარგმანი» — ჭეშმარიტი ქართული. ინგლისური და რუსული პარალელურად. კლიენტი არასოდეს ცვლის ენას." },
        { t: "ლიდები ავტომატურად გროვდება", d: "სახელი, ნომერი, კონტექსტი — ყველაფერი CRM-ში ან Email-ში გადმოდის. ცივი ლიდი არ რჩება." },
        { t: "რეალდროული ანალიტიკა", d: "რომელი კითხვები ხშირია, საიდან მოდიან, რა საათში ცხელია. Advanced charts Pro+ პლანებზე." },
        { t: "CRM და Zapier ინტეგრაცია", d: "Notion, HubSpot, Google Sheets, Slack — webhook-ით ან Zapier-ით ნებისმიერ ხელსაწყოსთან აერთებ." },
        { t: "Setup — 10 წუთი, კოდის გარეშე", d: "შენი ვებსაიტის URL ჩაწერე → AI თვითონ წაიკითხავს კონტენტს და FAQ-ს. დეველოპერი არ გჭირდება." },
        { t: "GDPR + Enterprise Security", d: "SOC 2 Type II ჩარჩო, end-to-end ენკრიფცია, ლიდების მონაცემები საქართველოს კანონების შესაბამისად." },
      ],
    },
    how: {
      kicker: "3 ნაბიჯი · 10 წუთი",
      title: "სამშაბათ დაიწყე. ხუთშაბათს გეყიდება.",
      sub: "არ გჭირდება დეველოპერი, არ გჭირდება IT გუნდი. შენი ვებსაიტის URL საკმარისია.",
      steps: [
        { t: "ასწავლე AI-ს შენი ბიზნესი", d: "შენი ვებსაიტის ლინკი ჩაწერე → Peit ავტომატურად ნახულობს გვერდებს, კითხულობს FAQ-ს და სწავლობს როგორ ისაუბროს.", note: "ან PDF / Google Docs / Notion ატვირთე" },
        { t: "მიამაგრე ვებსაიტს ერთი ხაზით", d: "კოპირდი 1 ხაზიანი script tag და ჩასვი შენი საიტის HEAD-ში. Telegram / Instagram / Messenger — ერთ კლიკზე ერთვება.", note: "WordPress, Shopify, Wix, Webflow — ყველგან მუშავს" },
        { t: "უყურე, როგორ მუშავს ფული", d: "AI 24/7 პასუხობს, ლიდები dashboard-ში გროვდება, შენ Email-ზე იღებ «ცხელი ლიდი» შეტყობინებას — რეალ-დროულად.", note: "ანალიტიკა + Email alerts + CSV export" },
      ],
    },
    industries: {
      kicker: "ინდუსტრიები",
      title: "ყველა სექტორისთვის",
      sub: "Peit ადაპტირდება შენი ბიზნესის სპეციფიკასთან — ერთ კვირაში.",
      items: [
        { t: "რესტორნები", d: "მენიუ, ჯავშანი, მიტანა — ავტომატური პასუხები 24/7", m: "+18 ჯავშანი/კვირა" },
        { t: "E-Commerce", d: "პროდუქტის ინფო, მარაგი, თვალყური — instant-ად", m: "3x კონვერსია" },
        { t: "სასტუმროები", d: "ნომრის ჯავშანი, ფასები, amenities — ქართულ-ინგლისური", m: "+25% booking" },
        { t: "უძრავი ქონება", d: "ობიექტების ინფო, ნახვის ჩანიშვნა, კვალიფიკაცია", m: "+15 ლიდი/კვირა" },
        { t: "კლინიკები", d: "ჩაწერა, სერვისები, ფასები — HIPAA-compliant", m: "-60% ზარი" },
        { t: "სპორტ-დარბაზები", d: "გრაფიკი, წევრობა, ტრიალი — ავტო-რეგისტრაცია", m: "+40% წევრი" },
        { t: "სილამაზის სალონები", d: "ჩაწერა, სერვისები, ფასები — round-the-clock", m: "0 გაცდენილი ჩაწერა" },
        { t: "საიურიდიო ფირმები", d: "პირველი კონსულტაცია, პრაქტიკის სფეროები, ღირებულება", m: "+8 კლიენტი/თვე" },
      ],
    },
    testimonials: {
      kicker: "კლიენტების შედეგები",
      title: "რას ამბობენ ჩვენი მომხმარებლები",
      sub: "რეალური შედეგები რეალური ბიზნესებიდან.",
      join: "შეუერთდი 10,000+ ბიზნესს რომლებიც უკვე იყენებენ Peit-ს",
      items: [
        { metric: "+12 გარიგება/თვე", quote: "ღამით ლიდებს ვკარგავდით. დილით ვიღვიძებდი 50 წაუკითხავ ჩატთან, ნახევარი უკვე გაცივებული. ახლა პასუხობენ წამში, საიტზე შემოსვლისთანავე. გასულ თვეში 12 გარიგება დავხურეთ ისეთი საუბრებიდან, რომლებიც ადრე უბრალოდ მკვდრდებოდა.", who: "Sarah Mitchell", role: "გაყიდვების ხელმძღვანელი, ელ-კომერცია", in: "SM" },
        { metric: "-73% ტიკეტები", quote: "ჩატბოტებზე ხელი ჩამოვიქნიე ორი წარუმატებელი ცდის შემდეგ. Peit პირველი იყო, ვიზე ბოდიში არ მომიწია. გუნდმა პირველი კვირის შემდეგ ლოგებში ჩახედა და ვერ გაარჩიეს, რომელი პასუხი იყო ბოტის. ტიკეტები 73 პროცენტით ჩამოვიდა.", who: "David Chen", role: "CTO, SaaS კომპანია", in: "DC" },
        { metric: "800+ პასუხი/კვირა", quote: "სამშაბათ დილით ჩავრთე, ყავამდეც ვერ მოვასწარი. პარასკევისთვის უკვე 800 კითხვაზე ჰქონდა ნაპასუხები, სანამ შვილის სასკოლო კონცერტზე ვიყავი. გულახდილად, დამავიწყდა რომ მუშაობდა.", who: "Marco Rossi", role: "ონლაინ მაღაზიის მფლობელი", in: "MR" },
      ],
    },
    pricing: {
      kicker: "ფასები",
      title: "ნაკლები ღირს ვიდრე ერთი support-ის სპეციალისტი.",
      sub: "და მუშაობს 24/7, არასოდეს ავადდება და 10x მეტ მოცულობას ამუშავებს.",
      compareA: "სრულ განაკვეთზე support-ის სპეციალისტი", compareAp: "~₾4,500/თვე",
      compareB: "Peit Pro — 33x უფრო იაფი", compareBp: "₾65/თვე",
      vs: "vs",
      cancel: "გაუქმება ნებისმიერ დროს — ნული რისკი",
      popular: "ყველაზე პოპულარული",
      plans: [
        { name: "Basic", price: "₾45", per: "/თვე", trial: "7-დღიანი ტრიალი ჩართულია", desc: "მცირე ბიზნესისთვის, რომელიც ახლა იწყებს", cta: "უფასოდ სცადე",
          feats: ["1,000 საუბარი/თვეში","1 AI ბოტი","ვებსაიტის ვიჯეტი","ქართული + ინგლისური + რუსული","Email support","7 დღე უფასოდ"] },
        { name: "Pro", price: "₾65", per: "/თვე", desc: "მზარდი ბიზნესისთვის — სრული ანალიტიკა, RAG AI", cta: "აირჩიე Pro", popular: true,
          feats: ["10,000 საუბარი/თვეში","5 AI ბოტი","AI Index (RAG retrieval)","Lead capture dashboard","დომენის allowlist","Telegram ინტეგრაცია","Priority support"] },
        { name: "Ultimate", price: "₾155", per: "/თვე", desc: "მსხვილი ბრენდისთვის — Instagram, FB, custom branding", cta: "აირჩიე Ultimate",
          feats: ["100,000 საუბარი/თვეში","20 AI ბოტი","Instagram + Facebook Messenger","«Powered by Peit»-ის მოშორება","Advanced ანალიტიკა","24/7 priority support","პერსონალური onboarding"] },
        { name: "Enterprise", price: "Custom", per: "", desc: "დიდი გუნდებისთვის და კომპანიებისთვის — ულიმიტო შეტყობინება, დედიკირებული ინფრასტრუქტურა, custom ინტეგრაციები და SLA გარანტია.", cta: "გუნდთან დაკავშირება", enterprise: true,
          feats: ["ულიმიტო საუბრები","დედიკირებული AI instance","Custom ინტეგრაცია","SLA + უსაფრთხო hosting"] },
      ],
      pay: "გადახდა TBC Bank-ით, Revolut-ით ან PayPal-ით",
    },
    finalCta: {
      title1: "ყოველი წუთი AI-ის გარეშე",
      title2: "არის კლიენტი, რომელიც კონკურენტთან მიდის.",
      sub: "შენი პირველი AI აგენტი 10 წუთში მუშავი იქნება.",
      note: "7 დღე უფასოდ · საკრედიტო ბარათი არ გჭირდება · გაუქმება ერთი კლიკით",
      cta: "უფასოდ დაიწყე ახლავე",
      join: "შეუერთდი 10,000+ ბიზნესს, რომელიც უკვე იყენებს Peit-ს",
    },
    faq: {
      kicker: "FAQ",
      title: "პასუხები ხშირ კითხვებზე",
      note: "ვერ იპოვე პასუხი?", noteLink: "მოგვწერე",
      items: [
        { q: "რა არის Peit?", a: "Peit არის ქართული AI ჩატბოტ პლატფორმა მცირე და საშუალო ბიზნესისთვის. ცვლის support-ის სპეციალისტს — 24/7 პასუხობს ვიზიტორებს ვებსაიტზე, Telegram-ში, Instagram-სა და Facebook-ში, აგროვებს ლიდებს და CRM-ში ატვირთავს." },
        { q: "ვისთვის გამოგვადგება?", a: "ნებისმიერი ბიზნესისთვის, რომელიც კლიენტებს ესაუბრება — ელ-კომერცია, რესტორნები, კლინიკები, სასტუმროები, სააგენტოები და სტარტაპები. თუ ერთსა და იმავე კითხვებს იმეორებ ან ლიდებს კარგავ — Peit შენთვისაა." },
        { q: "პროგრამისტი მჭირდება?", a: "არა. ატვირთე დოკუმენტები ან მიეცი ვებსაიტის URL, ჩასვი 1 ხაზიანი script tag (ან ერთი კლიკით დააკავშირე Telegram/Instagram) — და AI აგენტი ცოცხალია. setup 10 წუთზე ნაკლებია." },
        { q: "რა არხებზე მუშავს Peit?", a: "ვებსაიტზე embeddable ვიჯეტით, Telegram-ში, Instagram-სა და Facebook Messenger-ში — ყველაფერი ერთი dashboard-იდან." },
        { q: "როგორ მუშაობს 7-დღიანი ტრიალი?", a: "Basic პლანის ახალი მომხმარებლები იღებენ 7-დღიან უფასო ტრიალს სრული წვდომით. ბარათი წინასწარ ფიქსირდება — თუ მე-7 დღემდე გააუქმებ, არაფერი ჩამოგეჭრება." },
        { q: "რომელ ენებზე საუბრობს?", a: "ქართულად ბუნებრივად, ასევე ინგლისურად და რუსულად — კლიენტის ენას ავტომატურად ცნობს და არ ცვლის." },
        { q: "სად ინახება ჩემი მონაცემები?", a: "ლიდების მონაცემები ინახება საქართველოს კანონმდებლობისა და GDPR-ის შესაბამისად, end-to-end ენკრიფციით, SOC 2 Type II ჩარჩოში." },
        { q: "რა ღირს?", a: "Basic — ₾45/თვე, Pro — ₾65/თვე, Ultimate — ₾155/თვე, Enterprise — custom. ყველა გეგმა გაუქმებადია ნებისმიერ დროს." },
      ],
    },
    footer: {
      tagline: "AI ასისტენტი ქართული ბიზნესისთვის. 24/7 პასუხები, მეტი კლიენტი.",
      colProduct: "პროდუქტი", colIndustries: "ინდუსტრიები", colLegal: "სამართლებრივი", colSupport: "Support",
      product: ["ფუნქციები","ფასები","როგორ მუშაობს","ბლოგი"],
      industries: ["რესტორნები","E-Commerce","სასტუმროები","უძრავი ქონება","კლინიკები","სალონები"],
      legal: ["სერვისის წესები","კონფიდენციალობა","GDPR DPA","Cookie პოლიტიკა"],
      copy: "© 2026 Peit. ყველა უფლება დაცულია.",
      made: "დამზადებულია ❤️ საქართველოში",
    },
    ready: { title: "მზად ხარ დასაწყებად?", sub: "7 დღე უფასო. კოდი არ სჭირდება. 10 წუთი setup.", cta: "უფასოდ სცადე ახლა" },
    dash: {
      title: "Dashboard", greeting: "გამარჯობა, თამარ",
      sub: "შენი AI აგენტი მუშაობს. აი რა ხდება ახლა.",
      live: "ცოცხალია",
      nav: ["მიმოხილვა","ლიდები","საუბრები","ანალიტიკა","ინტეგრაციები","პარამეტრები"],
      kpis: [
        { l: "ახალი ლიდები (7 დღე)", v: "84", d: "+23%" },
        { l: "საუბრები დღეს", v: "312", d: "+12%" },
        { l: "საშ. პასუხის დრო", v: "0.8წმ", d: "−0.1" },
        { l: "კონვერსია", v: "31%", d: "+4%" },
      ],
      leadsTitle: "ბოლო ლიდები", leadsSub: "რეალ-დროულად გროვდება",
      cols: ["სახელი","არხი","კითხვა","სტატუსი","დრო"],
      statuses: { hot: "ცხელი", new: "ახალი", won: "მოგებული" },
      convTitle: "საუბრების მოცულობა", convSub: "ბოლო 14 დღე",
      chTitle: "არხების განაწილება",
      topTitle: "ხშირი კითხვები",
      exportCsv: "CSV ექსპორტი", viewAll: "ყველას ნახვა",
    },
  },

  en: {
    nav: { how: "How it works", pricing: "Pricing", industries: "Industries", blog: "Blog", signin: "Sign in", signup: "Try free", dashboard: "Dashboard" },
    hero: {
      badge: "+12 leads/week — from after-hours traffic",
      title1: "Your customer is waiting.",
      title2: "Your business — is asleep.",
      sub: "Upload an FAQ or drop a website URL — in 10 minutes Peit becomes your business's AI assistant. Answers in Georgian, 24/7, on your website, Telegram and Instagram.",
      cta1: "Start 7-day free trial",
      cta2: "How it works — 2 min",
      note: "No credit card needed · Cancel in one click",
      stat1: "0.8s", stat1l: "avg. response time",
      stat2: "3.2x", stat2l: "more conversions",
      stat3: "24/7", stat3l: "never sleeps",
    },
    chat: {
      name: "Peit Assistant", status: "Live · 0.8s", avg: "0.8s avg",
      placeholder: "Type your question...",
      msgs: [
        { who: "user", t: "Hi, are you open at 11pm?" },
        { who: "bot", t: "Hi! 👋 We take online orders 24/7. Delivery in Tbilisi — up to 40 min. What would you like to order?" },
        { who: "user", t: "I'd like two pizzas, where do I send the link?" },
        { who: "bot", t: "Sending it now — I've saved your number too. Pay by card or on delivery. ✅ Lead saved." },
      ],
    },
    social: {
      trust: "10,000+ businesses trust us",
      sub: "Georgia's fastest-growing AI platform",
      rating: "4.9", ratingNote: "(320+ reviews)",
      logos: ["Online Shop GE","MarShop","SaaS Startup","Tbilisi Resto","LegalPro GE","FitClub GE","GeoHotel","BeautyStudio","RealEstate GE","MediClinic","TechStartup","FoodDelivery"],
    },
    features: {
      kicker: "Features",
      title: "Everything in one place — working in your place",
      sub: "One platform, every channel, every language. You just see the results.",
      items: [
        { t: "24/7 — never sleeps", d: "Night, weekend and holiday traffic is no longer lost. Every visitor gets an answer in 0.8 seconds." },
        { t: "Website, Telegram, Instagram", d: "One bot — every channel. Conversations, leads and analytics collected in one dashboard." },
        { t: "Speaks Georgian naturally", d: "Not 'translation' — true Georgian. English and Russian in parallel. The customer never switches language." },
        { t: "Leads collected automatically", d: "Name, number, context — all pushed to your CRM or Email. No cold lead left behind." },
        { t: "Real-time analytics", d: "Which questions are frequent, where they come from, what hour is hot. Advanced charts on Pro+ plans." },
        { t: "CRM & Zapier integration", d: "Notion, HubSpot, Google Sheets, Slack — connect to any tool via webhook or Zapier." },
        { t: "Setup — 10 minutes, no code", d: "Enter your website URL → the AI reads your content and FAQ itself. No developer needed." },
        { t: "GDPR + Enterprise Security", d: "SOC 2 Type II framework, end-to-end encryption, lead data compliant with Georgian law." },
      ],
    },
    how: {
      kicker: "3 steps · 10 minutes",
      title: "Start Tuesday. Selling by Thursday.",
      sub: "No developer, no IT team. Your website URL is enough.",
      steps: [
        { t: "Teach the AI your business", d: "Drop your website link → Peit automatically crawls pages, reads the FAQ and learns how to talk.", note: "or upload PDF / Google Docs / Notion" },
        { t: "Attach it with one line", d: "Copy a 1-line script tag and paste it into your site's HEAD. Telegram / Instagram / Messenger — connect in one click.", note: "WordPress, Shopify, Wix, Webflow — works everywhere" },
        { t: "Watch the money work", d: "The AI answers 24/7, leads collect in the dashboard, you get a 'hot lead' email — in real time.", note: "Analytics + Email alerts + CSV export" },
      ],
    },
    industries: {
      kicker: "Industries",
      title: "For every sector",
      sub: "Peit adapts to your business specifics — in one week.",
      items: [
        { t: "Restaurants", d: "Menu, booking, delivery — automatic answers 24/7", m: "+18 bookings/week" },
        { t: "E-Commerce", d: "Product info, stock, tracking — instantly", m: "3x conversion" },
        { t: "Hotels", d: "Room booking, prices, amenities — Georgian-English", m: "+25% booking" },
        { t: "Real Estate", d: "Listing info, viewing scheduling, qualification", m: "+15 leads/week" },
        { t: "Clinics", d: "Booking, services, prices — HIPAA-compliant", m: "-60% calls" },
        { t: "Gyms", d: "Schedule, membership, trial — auto-registration", m: "+40% members" },
        { t: "Salons", d: "Booking, services, prices — round-the-clock", m: "0 missed bookings" },
        { t: "Law Firms", d: "First consultation, practice areas, pricing", m: "+8 clients/month" },
      ],
    },
    testimonials: {
      kicker: "Customer results",
      title: "What our customers say",
      sub: "Real results from real businesses.",
      join: "Join 10,000+ businesses already using Peit",
      items: [
        { metric: "+12 deals/mo", quote: "We were bleeding leads at night. I'd wake up to 50 unread chats, half already cold. Now they're answered in a second, the moment someone hits the site. Last month we closed 12 deals from conversations that used to just die.", who: "Sarah Mitchell", role: "Head of Sales, E-commerce", in: "SM" },
        { metric: "-73% tickets", quote: "I'd given up on chatbots after two failed tries. Peit was the first one I didn't have to apologize for. After week one the team checked the logs and couldn't tell which replies were the bot's. Tickets dropped 73 percent.", who: "David Chen", role: "CTO, SaaS Company", in: "DC" },
        { metric: "800+ answers/wk", quote: "Switched it on Tuesday morning, didn't even finish my coffee. By Friday it had answered 800 questions while I was at my kid's school concert. Honestly, I forgot it was running.", who: "Marco Rossi", role: "Online store owner", in: "MR" },
      ],
    },
    pricing: {
      kicker: "Pricing",
      title: "Costs less than one support hire.",
      sub: "And it works 24/7, never gets sick, and handles 10x the volume.",
      compareA: "Full-time support agent", compareAp: "~₾4,500/mo",
      compareB: "Peit Pro — 33x cheaper", compareBp: "₾65/mo",
      vs: "vs",
      cancel: "Cancel anytime — zero risk",
      popular: "Most popular",
      plans: [
        { name: "Basic", price: "₾45", per: "/mo", trial: "7-day trial included", desc: "For small businesses just starting out", cta: "Try free",
          feats: ["1,000 conversations/mo","1 AI bot","Website widget","Georgian + English + Russian","Email support","7 days free"] },
        { name: "Pro", price: "₾65", per: "/mo", desc: "For growing businesses — full analytics, RAG AI", cta: "Choose Pro", popular: true,
          feats: ["10,000 conversations/mo","5 AI bots","AI Index (RAG retrieval)","Lead capture dashboard","Domain allowlist","Telegram integration","Priority support"] },
        { name: "Ultimate", price: "₾155", per: "/mo", desc: "For larger brands — Instagram, FB, custom branding", cta: "Choose Ultimate",
          feats: ["100,000 conversations/mo","20 AI bots","Instagram + Facebook Messenger","Remove 'Powered by Peit'","Advanced analytics","24/7 priority support","Personal onboarding"] },
        { name: "Enterprise", price: "Custom", per: "", desc: "For large teams and companies — unlimited messaging, dedicated infrastructure, custom integrations and an SLA guarantee.", cta: "Contact the team", enterprise: true,
          feats: ["Unlimited conversations","Dedicated AI instance","Custom integration","SLA + secure hosting"] },
      ],
      pay: "Pay with TBC Bank, Revolut or PayPal",
    },
    finalCta: {
      title1: "Every minute without AI",
      title2: "is a customer going to a competitor.",
      sub: "Your first AI agent will be live in 10 minutes.",
      note: "7 days free · No credit card · Cancel in one click",
      cta: "Start free now",
      join: "Join 10,000+ businesses already using Peit",
    },
    faq: {
      kicker: "FAQ",
      title: "Answers to common questions",
      note: "Didn't find an answer?", noteLink: "Write to us",
      items: [
        { q: "What is Peit?", a: "Peit is a Georgian AI chatbot platform for small and medium businesses. It replaces a support agent — answering visitors 24/7 on your website, Telegram, Instagram and Facebook, collecting leads and pushing them to your CRM." },
        { q: "Who is it for?", a: "Any business that talks to customers — e-commerce, restaurants, clinics, hotels, agencies and startups. If you repeat the same questions or lose leads, Peit is for you." },
        { q: "Do I need a developer?", a: "No. Upload documents or give a website URL, paste a 1-line script tag (or connect Telegram/Instagram in one click) — and your AI agent is live. Setup takes under 10 minutes." },
        { q: "What channels does Peit work on?", a: "On your website via an embeddable widget, on Telegram, Instagram and Facebook Messenger — all from one dashboard." },
        { q: "How does the 7-day trial work?", a: "New Basic plan users get a 7-day free trial with full access. Your card is registered upfront — if you cancel before day 7, nothing is charged." },
        { q: "What languages does it speak?", a: "Georgian naturally, plus English and Russian — it detects the customer's language automatically and never switches." },
        { q: "Where is my data stored?", a: "Lead data is stored compliant with Georgian law and GDPR, with end-to-end encryption, within a SOC 2 Type II framework." },
        { q: "What does it cost?", a: "Basic — ₾45/mo, Pro — ₾65/mo, Ultimate — ₾155/mo, Enterprise — custom. Every plan is cancellable anytime." },
      ],
    },
    footer: {
      tagline: "AI assistant for Georgian business. 24/7 answers, more customers.",
      colProduct: "Product", colIndustries: "Industries", colLegal: "Legal", colSupport: "Support",
      product: ["Features","Pricing","How it works","Blog"],
      industries: ["Restaurants","E-Commerce","Hotels","Real Estate","Clinics","Salons"],
      legal: ["Terms of Service","Privacy","GDPR DPA","Cookie Policy"],
      copy: "© 2026 Peit. All rights reserved.",
      made: "Made with ❤️ in Georgia",
    },
    ready: { title: "Ready to start?", sub: "7 days free. No code. 10-minute setup.", cta: "Try free now" },
    dash: {
      title: "Dashboard", greeting: "Hello, Tamar",
      sub: "Your AI agent is working. Here's what's happening now.",
      live: "Live",
      nav: ["Overview","Leads","Conversations","Analytics","Integrations","Settings"],
      kpis: [
        { l: "New leads (7d)", v: "84", d: "+23%" },
        { l: "Conversations today", v: "312", d: "+12%" },
        { l: "Avg. response time", v: "0.8s", d: "−0.1" },
        { l: "Conversion", v: "31%", d: "+4%" },
      ],
      leadsTitle: "Recent leads", leadsSub: "collected in real time",
      cols: ["Name","Channel","Question","Status","Time"],
      statuses: { hot: "Hot", new: "New", won: "Won" },
      convTitle: "Conversation volume", convSub: "Last 14 days",
      chTitle: "Channel split",
      topTitle: "Top questions",
      exportCsv: "Export CSV", viewAll: "View all",
    },
  },
};

// Russian translation (real, not an English fallback).
const RU = {
  nav: { how: "Как работает", pricing: "Цены", industries: "Отрасли", blog: "Блог", signin: "Войти", signup: "Попробовать бесплатно", dashboard: "Панель" },
  hero: {
    badge: "+12 лидов в неделю — из ночного трафика",
    title1: "Клиент ждёт.",
    title2: "А ваш бизнес — спит.",
    sub: "Загрузите FAQ или дайте ссылку на сайт — за 10 минут Peit станет AI-ассистентом вашего бизнеса. Отвечает 24/7 на сайте, в Telegram и Instagram.",
    cta1: "7 дней бесплатно",
    cta2: "Как это работает — 2 мин",
    note: "Без карты · Отмена в один клик",
    stat1: "0.8с", stat1l: "среднее время ответа",
    stat2: "3.2x", stat2l: "больше конверсий",
    stat3: "24/7", stat3l: "никогда не спит",
  },
  chat: {
    name: "Peit Assistant", status: "Онлайн · 0.8с", avg: "0.8с avg",
    placeholder: "Напишите свой вопрос...",
    msgs: [
      { who: "user", t: "Здравствуйте, вы работаете в 23:00?" },
      { who: "bot", t: "Здравствуйте! 👋 Онлайн-заказы принимаем 24/7. Доставка по Тбилиси — до 40 минут. Что хотите заказать?" },
      { who: "user", t: "Хочу две пиццы, куда отправить ссылку?" },
      { who: "bot", t: "Сейчас отправлю — и зафиксировал ваш номер. Оплата картой или на месте. ✅ Лид сохранён." },
    ],
  },
  social: {
    trust: "Нам доверяют 10 000+ бизнесов",
    sub: "Самая быстрорастущая AI-платформа в Грузии",
    rating: "4.9", ratingNote: "(320+ отзывов)",
    logos: ["Online Shop GE","MarShop","SaaS стартап","Tbilisi Resto","LegalPro GE","FitClub GE","GeoHotel","BeautyStudio","RealEstate GE","MediClinic","TechStartup","FoodDelivery"],
  },
  features: {
    kicker: "Возможности",
    title: "Всё в одном месте — работает за вас",
    sub: "Одна платформа, все каналы, все языки. Вы видите только результат.",
    items: [
      { t: "24/7 — никогда не спит", d: "Ночной трафик, выходные и праздники больше не теряются. Каждый посетитель получает ответ за 0.8 секунды." },
      { t: "Сайт, Telegram, Instagram", d: "Один бот — на всех каналах. Диалоги, лиды и аналитика собираются в одной панели." },
      { t: "Естественный грузинский", d: "Не «перевод» — настоящий грузинский. Параллельно английский и русский. Клиент не меняет язык." },
      { t: "Лиды собираются автоматически", d: "Имя, телефон, контекст — всё попадает в CRM или на Email. Ни один лид не пропадёт." },
      { t: "Аналитика в реальном времени", d: "Какие вопросы частые, откуда приходят, в какие часы пик. Advanced-графики на Pro+." },
      { t: "Интеграции CRM и Zapier", d: "Notion, HubSpot, Google Sheets, Slack — через webhook или Zapier к любому инструменту." },
      { t: "Настройка — 10 минут, без кода", d: "Введите URL сайта → AI сам прочитает контент и FAQ. Разработчик не нужен." },
      { t: "GDPR + Enterprise Security", d: "SOC 2 Type II, end-to-end шифрование, данные лидов по закону." },
    ],
  },
  how: {
    kicker: "3 шага · 10 минут",
    title: "Начните во вторник. В четверг — продажи.",
    sub: "Не нужен разработчик, не нужна IT-команда. Достаточно URL вашего сайта.",
    steps: [
      { t: "Обучите AI вашему бизнесу", d: "Введите ссылку на сайт → Peit автоматически просматривает страницы, читает FAQ и учится говорить.", note: "Или загрузите PDF / Google Docs / Notion" },
      { t: "Подключите к сайту одной строкой", d: "Скопируйте 1 строку script-тега и вставьте в HEAD сайта. Telegram / Instagram / Messenger — в один клик.", note: "WordPress, Shopify, Wix, Webflow — везде работает" },
      { t: "Смотрите, как работают деньги", d: "AI отвечает 24/7, лиды собираются в панели, вы получаете уведомление «горячий лид» на Email — в реальном времени.", note: "Аналитика + Email-уведомления + CSV-экспорт" },
    ],
  },
  industries: {
    kicker: "Отрасли",
    title: "Для каждого сектора",
    sub: "Peit адаптируется к специфике вашего бизнеса — за неделю.",
    items: [
      { t: "Рестораны", d: "Меню, бронь, доставка — автоответы 24/7", m: "+18 броней/неделя" },
      { t: "E-Commerce", d: "Инфо о товаре, наличие, трекинг — мгновенно", m: "3x конверсия" },
      { t: "Отели", d: "Бронь номеров, цены, удобства — груз.-англ.", m: "+25% booking" },
      { t: "Недвижимость", d: "Инфо об объектах, запись на просмотр, квалификация", m: "+15 лидов/неделя" },
      { t: "Клиники", d: "Запись, услуги, цены — HIPAA-compliant", m: "-60% звонков" },
      { t: "Фитнес-залы", d: "Расписание, абонементы, пробное — авто-регистрация", m: "+40% участников" },
      { t: "Салоны красоты", d: "Запись, услуги, цены — круглосуточно", m: "0 пропущенных записей" },
      { t: "Юр. фирмы", d: "Первая консультация, сферы практики, стоимость", m: "+8 клиентов/месяц" },
    ],
  },
  testimonials: {
    kicker: "Результаты клиентов",
    title: "Что говорят наши пользователи",
    sub: "Реальные результаты реальных бизнесов.",
    join: "Присоединяйтесь к 10 000+ бизнесов, которые уже используют Peit",
    items: [
      { metric: "+12 сделок/месяц", quote: "Ночью теряли лиды. Утром просыпался с 50 непрочитанными чатами, половина уже остыла. Теперь отвечают за секунду, сразу при заходе на сайт. В прошлом месяце закрыли 12 сделок из диалогов, которые раньше просто умирали.", who: "Sarah Mitchell", role: "Руководитель продаж, e-commerce", in: "SM" },
      { metric: "-73% тикетов", quote: "Махнул рукой на чат-ботов после двух неудач. Peit был первым, за кого не пришлось извиняться. Команда через неделю заглянула в логи и не смогла различить, какой ответ дал бот. Тикеты упали на 73%.", who: "David Chen", role: "CTO, SaaS-компания", in: "DC" },
      { metric: "800+ ответов/неделя", quote: "Включил во вторник утром, не успел допить кофе. К пятнице бот ответил на 800 вопросов, пока я был на школьном концерте сына. Честно — забыл, что он работает.", who: "Marco Rossi", role: "Владелец онлайн-магазина", in: "MR" },
    ],
  },
  pricing: {
    kicker: "Цены",
    title: "Дешевле одного сотрудника поддержки.",
    sub: "И работает 24/7, никогда не болеет и обрабатывает в 10 раз больше.",
    compareA: "Сотрудник поддержки на полную ставку", compareAp: "~₾4,500/мес",
    compareB: "Peit Pro — в 33 раза дешевле", compareBp: "₾65/мес",
    vs: "vs",
    cancel: "Отмена в любой момент — ноль риска",
    popular: "Самый популярный",
    plans: [
      { name: "Basic", price: "₾45", per: "/мес", trial: "7-дневный триал включён", desc: "Для малого бизнеса, который начинает", cta: "Попробовать бесплатно",
        feats: ["1 000 диалогов/мес","1 AI-бот","Виджет для сайта","Грузинский + английский + русский","Email-поддержка","7 дней бесплатно"] },
      { name: "Pro", price: "₾65", per: "/мес", desc: "Для растущего бизнеса — полная аналитика, RAG AI", cta: "Выбрать Pro", popular: true,
        feats: ["10 000 диалогов/мес","5 AI-ботов","AI Index (RAG retrieval)","Lead capture dashboard","Allowlist доменов","Интеграция Telegram","Приоритетная поддержка"] },
      { name: "Ultimate", price: "₾155", per: "/мес", desc: "Для крупного бренда — Instagram, FB, кастом-брендинг", cta: "Выбрать Ultimate",
        feats: ["100 000 диалогов/мес","20 AI-ботов","Instagram + Facebook Messenger","Убрать «Powered by Peit»","Расширенная аналитика","24/7 приоритетная поддержка","Персональный onboarding"] },
      { name: "Enterprise", price: "Custom", per: "", desc: "Для больших команд и компаний — безлимит сообщений, выделенная инфраструктура, кастом-интеграции и SLA-гарантия.", cta: "Связаться с командой", enterprise: true,
        feats: ["Безлимит диалогов","Выделенный AI-instance","Кастом-интеграция","SLA + безопасный hosting"] },
    ],
    pay: "Оплата через TBC Bank, Revolut или PayPal",
  },
  finalCta: {
    title1: "Каждая минута без AI",
    title2: "— это клиент, который уходит к конкуренту.",
    sub: "Ваш первый AI-агент заработает за 10 минут.",
    note: "7 дней бесплатно · без карты · отмена в один клик",
    cta: "Начать бесплатно сейчас",
    join: "Присоединяйтесь к 10 000+ бизнесов, которые уже используют Peit",
  },
  faq: {
    kicker: "FAQ",
    title: "Ответы на частые вопросы",
    note: "Не нашли ответ?", noteLink: "Напишите нам",
    items: [
      { q: "Что такое Peit?", a: "Peit — грузинская AI-платформа чат-ботов для малого и среднего бизнеса. Заменяет сотрудника поддержки — 24/7 отвечает посетителям на сайте, в Telegram, Instagram и Facebook, собирает лиды и загружает в CRM." },
      { q: "Кому подойдёт?", a: "Любому бизнесу, который общается с клиентами — e-commerce, рестораны, клиники, отели, агентства и стартапы. Если повторяете одни и те же вопросы или теряете лиды — Peit для вас." },
      { q: "Нужен ли программист?", a: "Нет. Загрузите документы или дайте URL сайта, вставьте 1 строку script-тега (или подключите Telegram/Instagram в один клик) — и AI-агент готов. Настройка меньше 10 минут." },
      { q: "На каких каналах работает Peit?", a: "На сайте через встраиваемый виджет, в Telegram, Instagram и Facebook Messenger — всё из одной панели." },
      { q: "Как работает 7-дневный триал?", a: "Новые пользователи плана Basic получают 7-дневный бесплатный триал с полным доступом. Карта фиксируется заранее — если отмените до 7-го дня, ничего не спишется." },
      { q: "На каких языках говорит?", a: "На грузинском естественно, а также на английском и русском — язык клиента определяется автоматически и не меняется." },
      { q: "Где хранятся мои данные?", a: "Данные лидов хранятся по законодательству Грузии и GDPR, с end-to-end шифрованием, в рамках SOC 2 Type II." },
      { q: "Сколько стоит?", a: "Basic — ₾45/мес, Pro — ₾65/мес, Ultimate — ₾155/мес, Enterprise — custom. Все планы можно отменить в любой момент." },
    ],
  },
  footer: {
    tagline: "AI-ассистент для грузинского бизнеса. Ответы 24/7, больше клиентов.",
    colProduct: "Продукт", colIndustries: "Отрасли", colLegal: "Юридическое", colSupport: "Поддержка",
    product: ["Возможности","Цены","Как работает","Блог"],
    industries: ["Рестораны","E-Commerce","Отели","Недвижимость","Клиники","Салоны"],
    legal: ["Условия сервиса","Конфиденциальность","GDPR DPA","Cookie-политика"],
    copy: "© 2026 Peit. Все права защищены.",
    made: "Сделано с ❤️ в Грузии",
  },
  ready: { title: "Готовы начать?", sub: "7 дней бесплатно. Без кода. Настройка 10 минут.", cta: "Попробовать сейчас" },
  dash: RAW.en.dash,
};

export type LandingContent = typeof RAW.ka;
export type LandingLang = 'ka' | 'en' | 'ru';
export const LANDING: Record<LandingLang, LandingContent> = {
  ka: RAW.ka as LandingContent,
  en: RAW.en as LandingContent,
  ru: RU as unknown as LandingContent,
};
